---
title: "T-test"
---

The t-test module allows comparing means of continuous variables of interest to known means or across two groups. There are four main types of comparisons. 

- Comparison of one-sample mean to a known mean
- Comparison of two groups from the same sample
- Comparison of two means from two different samples
- Comparison of two paired means

`Ttest()` is the class that implements all four type of comparisons. To run a comparison, the user call the method `compare()` with the appropriate parameters.

```{python}
#| echo: true

from pprint import pprint

from samplics.datasets import load_auto
from samplics.categorical.comparison import Ttest
```

# Comparison of one-sample mean to a knowm mean

For this comparison, the mean of a continuous variable, i.e. mpg, is compared to a know mean. In the example below, the user is testing whether the average mpg is equal to 20. Hence, the null hypothesis is **H0: mean(mpg) = 20**. There are three possible alternatives for this null hypotheses:

- Ha: mean(mpg) < 20 (less_than alternative)
- Ha: mean(mpg) > 20 (greater_than alternative)
- Ha: mean(mpg) != 20 (not_equal alternative)

All three alternatives are automatically computed by the method `compare()`. This behavior is similar across the four type of comparisons. 

```{python}
#| echo: true

# Load Auto sample data
auto_dict = load_auto()
auto = auto_dict["data"]
mpg = auto["mpg"]

one_sample_known_mean = Ttest(samp_type="one-sample")
one_sample_known_mean.compare(y=mpg, known_mean=20)

print(one_sample_known_mean)
```

The print below shows the information encapsulated in the object. `point_est` provides the sample mean. Similarly, `stderror`, `stddev`, `lower_ci`, and `upper_ci` provide the standard error, standard deviation, lower bound confidence interval (CI), and upper bound CI, respectively. The class member `stats` provides the statistics related to the three t-tests (for the three alternative hypothesis). There is additional information encapsulated in the object as shown below. 

```{python}
#| echo: true

pprint(one_sample_known_mean.__dict__)
```

# Comparison of two groups from the same sample 

This type of comparison is used when the two groups are from the sample. For example, after running a survey, the user want to know if the domestic cars have the same mpg on average compare to the foreign cars. The parameter `group` indicates the categorical variable. NB: note that, at this point, `Ttest()` does not take into account potential dependencies between groups. 

```{python}
#| echo: true

foreign = auto["foreign"]

one_sample_two_groups = Ttest(samp_type="one-sample")
one_sample_two_groups.compare(y=mpg, group=foreign)

print(one_sample_two_groups)
```

Since there are two groups for this comparison, the sample mean, standard error, standard deviation, lower bound CI, and upper bound CI are provided by group as Python dictionaries. The class member `stats` provides statistics for the comparison assuming both equal and unequal variances.

```{python}
#| echo: true

print("These are the group means for mpg:")
pprint(one_sample_two_groups.point_est)
```

```{python}
#| echo: true

print(f"These are the group standard error for mpg:")
pprint(one_sample_two_groups.stderror)
```

```{python}
#| echo: true

print("These are the group standard deviation for mpg:")
pprint(one_sample_two_groups.stddev)
```

```{python}
#| echo: true

print("These are the computed statistics:")
pprint(one_sample_two_groups.stats)
```

# Comparison of two means from two different samples

This type of comparison should be used when the two groups come from different samples or different strata. The group are assumed independent. Otherwise, the information is similar to the previous test. Note that, when instantiating the class, we used `samp_type="two-sample"`. 

```{python}
#| echo: true

two_samples_unpaired = Ttest(samp_type="two-sample", paired=False)
two_samples_unpaired.compare(y=mpg, group=foreign)

print(two_samples_unpaired)
```

```{python}
#| echo: true

print("These are the group means for mpg:")
pprint(two_samples_unpaired.point_est)
```

```{python}
#| echo: true

print("These are the group standard error for mpg:") 
pprint(two_samples_unpaired.stderror)
```

```{python}
#| echo: true

print("These are the group standard deviation for mpg:")
pprint(two_samples_unpaired.stddev)
```

```{python}
#| echo: true

print("These are the computed statistics:")
pprint(two_samples_unpaired.stats)
```

# Comparison of two paired means

When two measures are taken from the same observations, the paired t-test is appropriate for comparing the means. 

```{python}
#| echo: true

two_samples_paired = Ttest(samp_type="two-sample", paired=True)
two_samples_paired.compare(y=auto[["y1", "y2"]], group=foreign)

print(two_samples_paired)
```

`varnames` can be used rename the variables

```{python}
#| echo: true

y1 = auto["y1"]
y2 = auto["y2"]

two_samples_paired = Ttest(samp_type="two-sample", paired=True)
two_samples_paired.compare(
    y=[y1, y2], 
    varnames= ["group_1", "gourp_2"], 
    group=foreign
    )

print(two_samples_paired)
```