---
title: "Selection of SSUs"
---

To select the second stage sample, we need the second stage frame which is the list of all the households in the 10 selected clusters (psus). DHS, PHIA, MICS and other large scale surveys visit the selected clusters and construct the list of all households in the selected clusters. 

Before starting the second stage selection, let us import the data from the first stage sampling information that is the first stage sample (psu_sample). For clarity, we explicitly import the packages and modules needed for this notebook. 


```{python}
#| echo: true

import numpy as np 
import pandas as pd 

from samplics import SelectMethod
from samplics.sampling import SampleSelection

# Load the selected PSUs 
psu_frame = pd.read_csv("./psu_frame.csv")
```

In this tutorial, we will simulate the second stage frame. For the simulation, assume that the psu frame was obtained from a previous census conducted several years before. We also assume that, the change in the number of households since the previous census follows a normal distribution with a mean equal to 5% higher than the census value and a variance of 0.15 times the number of households from the census. Under these assumptions, we generate the following second stage frame of households. Note that the frame is created only for the selected PSUs.

```{python}
#| echo: true

# Create a synthetic second stage frame
census_size = psu_frame.loc[
    psu_frame["psu_sample"] == 1, 
    "number_households_census"
].values
stratum_names = psu_frame.loc[
    psu_frame["psu_sample"] == 1, 
    "region"
    ].values
cluster = psu_frame.loc[psu_frame["psu_sample"] == 1, "cluster"].values

np.random.seed(15)

listing_size = np.zeros(census_size.size)
for k in range(census_size.size):
    listing_size[k] = np.random.normal(
        1.05 * census_size[k], 0.15 * census_size[k]
        )

listing_size = listing_size.astype(int)
hh_id = rr_id = cl_id = []
for k, s in enumerate(listing_size):
    hh_k1 = np.char.array(np.repeat(stratum_names[k], s)).astype(str)
    hh_k2 = np.char.array(np.arange(1, s + 1)).astype(str)
    cl_k = np.repeat(cluster[k], s)
    hh_k = np.char.add(np.char.array(cl_k).astype(str), hh_k2)
    hh_id = np.append(hh_id, hh_k)
    rr_id = np.append(rr_id, hh_k1)
    cl_id = np.append(cl_id, cl_k)

ssu_frame = pd.DataFrame(cl_id.astype(int))
ssu_frame.rename(columns={0: "cluster"}, inplace=True)
ssu_frame["region"] = rr_id
ssu_frame["household"] = hh_id

nb_obs = 15
print(f"\nFirst {nb_obs} observations of the SSU frame\n")
ssu_frame.head(nb_obs)
```

```{python}
#| echo: true

psu_sample = psu_frame.loc[psu_frame["psu_sample"] == 1]
ssu_counts = ssu_frame.groupby("cluster").count()
ssu_counts.drop(columns="region", inplace=True)
ssu_counts.reset_index(inplace=True)
ssu_counts.rename(
    columns={"household": "number_households_listed"}, 
    inplace=True
    )

pd.merge(
    psu_sample[["cluster", "region", "number_households_census"]],
    ssu_counts[["cluster", "number_households_listed"]],
    on=["cluster"],
)
```

According to the simulated second stage frame, we get the same number of households in cluster 7 as the census. However, in strata 10, 16, 29, and 64, we listed more households than during than the census. And finally, we found less households in the remaining clusters than the census. 

Now that we have a second stage frame, let's use *samplics* to calculate the probabilities of selection and to select a sample. The second stage sample size is 150 households and the strategy is to select 15 households per cluster. 

# SSU (household) Probability of Selection

The second stage probabilities of selection are conditional on the first stage realization. For this stage, simple random selection (srs) and systematic selection(sys) are common methods used to select households. For this example, we use srs to select 15 households from each cluster. Conditionally to teh first stage, the second stage selection is a stratified srs where the clusters are the strata. More generally, we have that \begin{equation} p_{hij} = \frac{m_{hi}}{M_{hi}^{'}} \end{equation} where $p_{hij}$ is the conditional probability of selection for unit $j$ from stratum $h$ and cluster $j$, $m_{hi}$ and $M_{hi}^{'}$ are the sample size and the number of secondary sampling units listed for stratum $h$ and cluster $j$, respectively.


In this scenario, sample size is the same in each stratum. Hence, the parameter *sample_size* does not need to be a Python dictionary; we will only provide 15 in the function call. 

```{python}
#| echo: true

stage2_design = SampleSelection(
    method=SelectMethod.srs_wor, strat=True, wr=False
)

ssu_frame["ssu_prob"] = stage2_design.inclusion_probs(
    ssu_frame["household"], 15, ssu_frame["cluster"]
)

ssu_frame.sample(20)
```

### SSU (household) Selection

The second stage sample is selected from the SSU frame (*ssu_frame*) using the variable *cluster* as the strat variable. The sample is selected without replacement according to the specification of the second stage design. Hence, both *ssu_sample* and *ssu_hits* sum to 150 and each selected household was hit only ounce (i.e. *ssu_hits* = 1).

```{python}
#| echo: true
np.random.seed(11)
ssu_sample, ssu_hits, ssu_probs = stage2_design.select(
    ssu_frame["household"], 15, ssu_frame["cluster"]
)

ssu_frame["ssu_sample"] = ssu_sample
ssu_frame["ssu_hits"] = ssu_hits
ssu_frame["ssu_probs"] = ssu_probs

ssu_frame[ssu_frame["ssu_sample"] == 1].sample(15)
```

Let's check that both *ssu_sample* and *ssu_hits* sum to 150 and each selected household was hit only ounce (i.e. *ssu_hits* = 1).

:::{style="font-size:0.9rem"}
```{python}
#| echo: true

print(f"The sum of `ssu_sample` is equal to: {ssu_frame['ssu_sample'].sum()}\n")
```

```{python}
#| echo: true

print(f"The sum of `ssu_hits` is equal to: {ssu_frame['ssu_hits'].sum()}\n")
```

```{python}
#| echo: true

print(f"The values of `ssu_hits` are: {np.unique(ssu_frame['ssu_hits']).tolist()}\n")
```
:::

To use systematic selection, we just need to replace `method=SelectMethod.srs_wor` by `method=SelectMethod.sys`. 

Another common approach is to use a rate for selecting the sample. Instead of selecting 15 households from 130 in the first cluster, we may want to select with a rate of 15/130, and similarly for the other clusters. 

```{python}
#| echo: true

rates = np.repeat(15, 10) / ssu_counts["number_households_listed"].values
ssu_rates = dict(zip(np.unique(ssu_frame["cluster"]), rates))
ssu_rates
```


```{python}
#| echo: true

np.random.seed(22)

stage2_design2 = SampleSelection(
    method=SelectMethod.sys, strat=True, wr=False
)

ssu_sample_r, ssu_hits_r, _ = stage2_design2.select(
    ssu_frame["household"], 
    stratum=ssu_frame["cluster"], 
    samp_rate=ssu_rates
)

ssu_sample2 = pd.DataFrame(
    data={
        "household": ssu_frame["household"],
        "ssu_sample_r": ssu_sample_r,
        "ssu_hits_r": ssu_hits_r,
    }
)

ssu_sample2.head(25)
```

Let's store the first and second stages samples. 

```{python}
#| echo: true

# First stage sample
psu_sample[["cluster", "region", "psu_prob"]].to_csv("psu_sample.csv")

# Second stage sample
ssu_sample = ssu_frame.loc[ssu_frame["ssu_sample"] == 1]
ssu_sample[["cluster", "household", "ssu_prob"]].to_csv("ssu_sample.csv")
```