---
title: "Sample Weight Adjustments"
---

The objective of this tutorial is to familiarize ourselves with *SampleWeight* the *samplics* class for adjusting sample weights. In practice, it is necessary to adjust base or design sample weights obtained directly from the random sample mechanism. These adjustments are done to correct for nonresponse, reduce effects of extreme/large weights, better align with known auxiliary information, and more. Specifically in this tutorial, we will:

- learn how to use the method *adjust()* to redistribute sample weights to account for nonresponse and unknown eligibility,
- learn how to use the method *poststratify()* to ensure that the sample weights sum to known control totals or that the relative distribution of domains is force to known distributions, 
- learn how to use the method *calibrate()* to adjust sample weight using auxiliary information under the regression model, 
- learn how to use the method *normalize()* to ensure that the sample weights sum to known constants. 

To run the code in this notebook, we will use the dataset that was developed in the previous tutorial on sample selection. 

```{python}
#| echo: true

import numpy as np
import pandas as pd

from samplics.datasets import load_psu_sample, load_ssu_sample
from samplics.weighting import SampleWeight
```
# Design (base) weight

The design weight is the inverse of the overall probability of selection which is the product of the first and second probabilities of selection. 

```{python}
#| echo: true

# Load PSU sample data
psu_sample_dict = load_psu_sample()
psu_sample = psu_sample_dict["data"]

# Load PSU sample data
ssu_sample_dict = load_ssu_sample()
ssu_sample = ssu_sample_dict["data"]

full_sample = pd.merge(
    psu_sample[["cluster", "region", "psu_prob"]], 
    ssu_sample[["cluster", "household", "ssu_prob"]], 
    on="cluster"
)

full_sample["inclusion_prob"] = full_sample["psu_prob"] * \
    full_sample["ssu_prob"]
full_sample["design_weight"] = 1 / full_sample["inclusion_prob"]

full_sample.head(15)
```

For the purposes of this illustration of handling non-response, we first need to incorporate some household non-response into our example. That is, we simulate the non-response status and store it in the variable *response_status*. The variable *response_status* has four possible values: *ineligible* which indicates that the sampling unit is not eligible for the survey, *respondent* which indicates that the sampling unit responded to the survey, *non-respondent* which indicates that the sampling unit did not respond to the survey, and *unknown* means that we are not able to infer the status of the sampling unit i.e. we do not know whether the sampling unit is eligible or not to the survey. 

```{python}
#| echo: true

np.random.seed(7)
full_sample["response_status"] = np.random.choice(
    ["ineligible", "respondent", "non-respondent", "unknown"], 
    size=full_sample.shape[0], 
    p=(0.10, 0.70, 0.15, 0.05)
)

full_sample[
    ["cluster", "region", "design_weight", "response_status"]
    ].head(15)
```

## Nonresponse adjustment

In general, the sample weights are adjusted to redistribute the sample weights of all eligible units for which there is no sufficient response (unit level nonresponse) to the sampling units that sufficiently responded to the survey. This adjustment is done within adjustment classes or domains. Note that the determination of the response categories (unit response, item response, ineligible, etc.) is outside of the scope of this tutorial. 

Also, the weights of the sampling units with unknown eligibility are redistributed to the rest of the sampling units. In general, ineligible sampling units receive weights from the sampling units with unknown eligibility since eligible sampling units can be part of the unknown pool. 

The method *adjust()* has a boolean parameter *unknown_to_inelig* which controls how the sample weights of the unknown is redistributed. By default, *adjust()* redistribute the sample weights of the sampling units of the unknown to the ineligibles (*unknown_to_inelig=True*). If we do not wish to redistribute the sample weights of the unknowns to the ineligibles then we just set the flag to False (*unknown_to_inelig=Fasle*).

In the snippet of code below, we adjust the weight within clusters that is we use clusters as our adjustment classes. Note that we run the nonresponse adjustment twice, the first time with *unknown_to_inelig=True* (*nr_weight*) and the second time with the flag equal to False (*nr_weight2*). With *unknown_to_inelig=True*, the ineligible received part of the sample weights from the unknowns. Hence, the sample weights for the respondent is less than when the flag is False. With *unknown_to_inelig=Fasle*, the ineligible did Not receive any weights from the unknowns. Hence, the sample weights for the ineligible units remain the same before and after adjustment. In a real survey, the statistician may decide on the best non-response strategy based on the available information.

```{python}
#| echo: true

status_mapping = {
    "in": "ineligible", 
    "rr": "respondent", 
    "nr": "non-respondent", 
    "uk": "unknown"
    }

full_sample["nr_weight"] = SampleWeight().adjust(
    samp_weight=full_sample["design_weight"],
    adj_class=full_sample[["region", "cluster"]],
    resp_status=full_sample["response_status"],
    resp_dict=status_mapping,
)

full_sample["nr_weight2"] = SampleWeight().adjust(
    samp_weight=full_sample["design_weight"],
    adj_class=full_sample[["region", "cluster"]],
    resp_status=full_sample["response_status"],
    resp_dict=status_mapping,
    unknown_to_inelig=False,
)

full_sample[[
    "cluster", 
    "region", 
    "design_weight", 
    "response_status", 
    "nr_weight", 
    "nr_weight2"
    ]].drop_duplicates().head(15)
```

:::{.callout-important}
The default call of *adjust()* expects standard codes for response status that is "in", "rr", "nr", and "uk" where "in" means ineligible, "rr" means respondent, "nr" means non-respondent, and "uk" means unknown eligibility.
:::

In the call above, if we omit the parameter *response_dict*, then the run would fail with an assertion error message. The current error message is the following: **The response status must only contains values in ('in', 'rr', 'nr', 'uk') or the mapping should be provided using response_dict parameter**. For the call to run without using *response_dict*, it is necessary that the response status takes only values in the standard codes i.e. ("in", "rr", "nr", "uk"). The variable associated with *response_status* can contain any code but a mapping is necessary when the response variable is not constructed using the standard codes.

To further illustrate the mapping of response status, let's assume that we have response_status2 which has the values 100 for ineligible, 200 for non-respondent, 300 for respondent, and 999 for unknown. 

```{python}
#| echo: true

response_status2 = np.repeat(100, full_sample["response_status"].shape[0])
response_status2[full_sample["response_status"] == "non-respondent"] = 200
response_status2[full_sample["response_status"] == "respondent"] = 300
response_status2[full_sample["response_status"] == "unknown"] = 999

pd.crosstab(response_status2, full_sample["response_status"])
```

To use *response_status2*, we need to map the values 100, 200, 300 and 999 to "in", "rr", "nr", and "uk". This mapping is done below using the Python dictionary *status_mapping2*. Using *status_mapping2* in the function call *adjust()* will lead to the same adjustment as in the previous run i.e. *nr_weight* and *nr_weight3* contain the same adjusted weights. 

```{python}
#| echo: true
#| warning: false

status_mapping2 = {"in": 100, "nr": 200, "rr": 300, "uk": 999}

full_sample["nr_weight3"] = SampleWeight().adjust(
    samp_weight=full_sample["design_weight"],
    adj_class=full_sample[["region", "cluster"]],
    resp_status=response_status2,
    resp_dict=status_mapping2,
)

full_sample[
    ["cluster", "region", "response_status", "nr_weight", "nr_weight3"]
    ].drop_duplicates().head()
```

If the response status variable only takes values "in", "nr", "rr" and "uk", then it is not necessary to provide the mapping dictionary to the function i.e. *resp_dict* can be omitted from the function call *adjust()*. 

```{python}
#| echo: true

response_status3 = np.repeat("in", full_sample["response_status"].shape[0])
response_status3[full_sample["response_status"] == "non-respondent"] = "nr"
response_status3[full_sample["response_status"] == "respondent"] = "rr"
response_status3[full_sample["response_status"] == "unknown"] = "uk"

full_sample["nr_weight4"] = SampleWeight().adjust(
    samp_weight=full_sample["design_weight"],
    adj_class=full_sample[["region", "cluster"]],
    resp_status=response_status3,
)

full_sample[
    ["cluster", "region", "response_status", "nr_weight", "nr_weight4"]
    ].drop_duplicates().head()
```

```{python}
#| echo: true

# Just dropping a couple of variables 
# not needed for the rest of the tutorial
full_sample.drop(
    columns=[
        "psu_prob", 
        "ssu_prob", 
        "inclusion_prob", 
        "nr_weight2", 
        "nr_weight3", 
        "nr_weight4"
        ], 
    inplace=True
)
```

## Poststratification 

Poststratification is useful to compensate for under-representation of the sample or to correct for nonsampling error. The most common poststratification method consists of adjusting the sample weights to ensure that they sum to **known** control values from **reliable** souces by adjustment classes (domains). Poststratification classes can be formed using variables beyond the ones involved in the sampling design. For example, socio-economic variables such as age group, gender, race and education are often used to form poststratification classes/cells.

:::{.callout-warning}
poststratifying to totals that are known to be out of date, and thus likely inaccurate and/or unreliable may not improve the estimate. Use this with caution.
:::

Let's assume that we have a reliable external source e.g. a recent census that provides the number of households by region. The external source has the following control data: 3700 households for East, 1500 for North, 2800 for South and 6500 for West. 

We use the method *poststratify()* to ensure that the poststratified sample weights (*ps_weight*) sum to the know control totals by region. Note that the control totals are provided using the Python dictionary *census_households*.


```{python}
#| echo: true

census_households = {"East": 3700, "North": 1500, "South": 2800, "West": 6500}

full_sample["ps_weight"] = SampleWeight().poststratify(
    samp_weight=full_sample["nr_weight"], 
    control=census_households, 
    domain=full_sample["region"]
)

full_sample.head(15)
```

The snippet of code below shows that the poststratified sample weights sum to the expected control totals that is 3700 households for East, 1500 for North, 2800 for South and 6500 for West. 

```{python}
#| echo: true

sum_of_weights = full_sample[
    ["region", "nr_weight", "ps_weight"]
    ].groupby("region").sum()
sum_of_weights.reset_index(inplace=True)
sum_of_weights.head()
```

The crosstable below shows that only one adjustment factor was calculated and applied per adjustment class or region. 

```{python}
#| echo: true

full_sample["ps_adj_fct"] = \
    round(full_sample["ps_weight"] / full_sample["nr_weight"], 12)

pd.crosstab(full_sample["ps_adj_fct"], full_sample["region"])
```

In some surveys, there is interest in keeping relative distribution of strata to some known distribution. For example, WHO EPI vaccination surveys often postratify sample weights to ensure that relative sizes of strata reflect offcial statistics e.g. census data. In most cases, the strata are based on some administrative divisions.  

For example, assume that according to census data that East contains 25% of the households, North contains 10%, South contains 20% and West contains 45%. We can poststratify using the snippet of code below. 

```{python}
#| echo: true

known_ratios = {"East": 0.25, "North": 0.10, "South": 0.20, "West": 0.45}
full_sample["ps_weight2"] = SampleWeight().poststratify(
    samp_weight=full_sample["nr_weight"], 
    factor=known_ratios, 
    domain=full_sample["region"]
)

full_sample.head()
```

```{python}
#| echo: true

sum_of_weights2 = full_sample[
    ["region", "nr_weight", "ps_weight2"]
    ].groupby("region").sum()
sum_of_weights2.reset_index(inplace=True)
sum_of_weights2["ratio"] = \
    sum_of_weights2["ps_weight2"] / sum(sum_of_weights2["ps_weight2"])
sum_of_weights2.head()
```

### Calibration 

Calibration is a more general concept for adjusting sample weights to sum to known constants. In this tutorial, we consider the generalized regression (GREG) class of calibration. Assume that we have $\hat{\mathbf{Y}} = \sum_{i \in s} w_i y_i$ and know population totals $\mathbf{X} = (\mathbf{X}_1, ..., \mathbf{X}_p)^T$ are available. Working under the model $Y_i | \mathbf{x}_i = \mathbf{x}^T_i \mathbf{\beta} + \epsilon_i$, the GREG estimator of the population total is 

$$\hat{\mathbf{Y}}_{GR} = \hat{\mathbf{Y}} + (\mathbf{X} - \hat{\mathbf{X}})^T\hat{\mathbf{B}}$$

where $\hat{\mathbf{B}}$ is the weighted least squares estimate of $\mathbf{\beta}$ and $\hat{\mathbf{X}}$ is the survey estimate of $\mathbf{X}$. The essential of the GREG approach is, under the regression model, to find the adjusted weights $w^{*}_i$ that are the closest to $w_i$, to minimize $h(z) = \frac{\sum_{i \in s} c_i(w_i - z_i)}{w_i}$.

Let us simulate three auxiliary variables that is education, poverty and under_five (number of children under five in the household) and assume that we have the following control totals.

- Total number of under five children: 6300 in the East, 4000 in the North, 6500 in the South and 14000 in the West. 
- Poverty (Yes: in poverty / No: not in poverty)

    | Region &nbsp;| Poverty &nbsp;| Number of households |
    |:--------|:--------:|:--------------------:|
    | East    |    No    |       2600           |
    |         |    Yes   |       1200           |
    | North   |    No    |       1500           |
    |         |    Yes   |        200           |
    | South   |    No    |       1800           |
    |         |    Yes   |       1100           |
    | West    |    No    |       4500           |
    |         |    Yes   |       2200           |

- Education (Low: less than secondary, Medium: secondary completed, and High: More than secondary)

    | Region &nbsp;| Education &nbsp;| Number of households |
    |:--------|:--------:|:------:|
    | East    | Low      | 2000   |
    |         | Medium   | 1400   |
    |         | High     |  350   |
    | North   | Low      |  550   |
    |         | Medium   |  700   |
    |         | High     |  250   |
    | South   | Low      | 1300   |
    |         | Medium   | 1200   |
    |         | High     |  350   |
    | West    | Low      | 2100   |
    |         | Medium   | 4000   |
    |         | High     |  500   |

```{python}
#| echo: true

np.random.seed(150)
full_sample["education"] = np.random.choice(
    ("Low", "Medium", "High"), 
    size=150, 
    p=(0.40, 0.50, 0.10)
    )
full_sample["poverty"] = np.random.choice((0, 1), size=150, p=(0.70, 0.30))
full_sample["under_five"] = np.random.choice(
    (0, 1, 2, 3, 4, 5), 
    size=150, 
    p=(0.05, 0.35, 0.25, 0.20, 0.10, 0.05)
    )

full_sample[[
    "cluster", 
    "region", 
    "household", 
    "nr_weight", 
    "education", 
    "poverty", 
    "under_five"
    ]].head()
```

We now will calibrate the nonreponse weight (*nr_weight*) to ensure that the estimated number of households in poverty is equal to 4,700 and the estimated total number of children under five is 30,8500. The control numbers 4,700 and 30,800 are obtained from the table above. 

The class *SampleWeight()* uses the method *calibrate(samp_weight, aux_vars, control, domain, scale, bounded, modified)* to adjust the weight using the GREG approach. 
* The contol values must be stored in a python dictionnary i.e. totals = {"poverty": 4700, "under_five": 30800}. In this case, we have two numerical variables poverty with values in {0, 1} and under_five with values in {0, 1, 2, 3, 4, 5}. 
* *aux_vars* is the matrix of covariates.

```{python}
#| echo: true

totals = {"poverty": 4700, "under_five": 30800}

full_sample["calib_weight"] = SampleWeight().calibrate(
    full_sample["nr_weight"], full_sample[["poverty", "under_five"]], totals
)

full_sample[["cluster", "region", "household", "nr_weight", "calib_weight"]].head(15)
```

We can confirm that the estimated totals for the auxiliary variables are equal to their control values.

```{python}
#| echo: true

poverty = full_sample["poverty"]
under_5 = full_sample["under_five"]
nr_weight = full_sample["nr_weight"]
calib_weight = full_sample["calib_weight"]

print(
    f"""\nTotal estimated number of poor households was 
    {sum(poverty*nr_weight):.2f} before adjustment and 
    {sum(poverty*calib_weight):.2f} after adjustment.\n"""
)
print(
    f"""Total estimated number of children under 5 was 
    {sum(under_5*nr_weight):.2f} before adjustment and 
    {sum(under_5*calib_weight):.2f} after adjustment.\n"""
)
```

If we want to control by domain then we can do so using the parameter *domain* of *calibrate()*. First we need to update the python dictionary holding the control values. Now, those values have to be provided for each domain. Note that the dictionary is now a nested dictionary where the higher level keys hold the domain values i.e. East, North, South and West. Then the higher level values of the dictionary are the dictionaries providing mapping for the auxiliary variables and the corresponding control values. 

```{python}
#| echo: true

totals_by_domain = {
    "East": {"poverty": 1200, "under_five": 6300},
    "North": {"poverty": 200, "under_five": 4000},
    "South": {"poverty": 1100, "under_five": 6500},
    "West": {"poverty": 2200, "under_five": 14000},
}

full_sample["calib_weight_d"] = SampleWeight().calibrate(
    full_sample["nr_weight"], 
    full_sample[["poverty", "under_five"]], 
    totals_by_domain, full_sample["region"]
)

full_sample[[
    "cluster", 
    "region", 
    "household", 
    "nr_weight", 
    "calib_weight", 
    "calib_weight_d"
    ]].head(15)
```

Note that the GREG domain estimates above do not have the additive property. That is the GREG domain estimates do not sum to the overal GREG estimate. To illustrate this, let's assume that we want to estimate the number of households. 

```{python}
#| echo: true

print(f"\nThe number of households using the overall GREG is: \
    {sum(full_sample['calib_weight']):.2f} \n")
print(f"The number of households using the domain GREG is: \
    {sum(full_sample['calib_weight_d']):.2f} \n")
```

:::{.callout-note}
If the additive flag is set to `True`, the sum of the domain estimates will be equal to the GREG overal estimate. 
:::


```{python}
#| echo: true

totals_by_domain = {
    "East": {"poverty": 1200, "under_five": 6300},
    "North": {"poverty": 200, "under_five": 4000},
    "South": {"poverty": 1100, "under_five": 6500},
    "West": {"poverty": 2200, "under_five": 14000},
}

calib_weight3 = SampleWeight().calibrate(
    full_sample["nr_weight"],
    full_sample[["poverty", "under_five"]],
    totals_by_domain,
    full_sample["region"],
    additive=True,
)
```

```{python}
#| echo: true

under_5 = np.array(full_sample["under_five"])
print(f"\nEach column can be used to estimate a domain: \
{np.sum(np.transpose(calib_weight3) * under_5, axis=1)}\n")
```

```{python}
#| echo: true

print(f"The number of households using the overall GREG is: \
{sum(full_sample['calib_weight']):.2f} \n")
```

```{python}
#| echo: true

print(f"The number of households using the domain GREG is: \
{sum(full_sample['calib_weight_d']):.2f} (additive=False)\n")
```

```{python}
#| echo: true

print(f"The number of households using the domain GREG is: \
{np.sum(np.transpose(calib_weight3)):.2f} (additive=True) \n")
```

## Normalization

DHS and MICS normalize the final sample weights to sum to the sample size. We can use the class method *normalize()* to ensure that the sample weight sum to some constant across the sample or by normalization domain e.g. stratum. 

:::{.callout-note}
*normalization* is mostly added here for completeness but it is sheldom to see sample weight normalize in large scale household surveys. One major downside of normalized weights is the Note that estimation of totals does not make sense with normalized weights. 
:::

```{python}
#| echo: true

full_sample["norm_weight"] = \
    SampleWeight().normalize(samp_weight=full_sample["nr_weight"])
full_sample[["cluster", "region", "nr_weight", "norm_weight"]].head(25)

print((full_sample.shape[0], full_sample["norm_weight"].sum()))
```

When *normalize()* is called with only the parameter *sample_weight* then the sample weights are normalize to sum to the length of the sample weight vector. 

```{python}
#| echo: true


full_sample["norm_weight2"] = \
    SampleWeight().normalize(
        samp_weight=full_sample["nr_weight"], 
        control=300
        )

print(full_sample["norm_weight2"].sum())
```

```{python}
#| echo: true

full_sample["norm_weight3"] = SampleWeight().normalize(
    samp_weight=full_sample["nr_weight"], 
    domain=full_sample["region"]
    )

weight_sum = full_sample.groupby(["region"]).sum()
weight_sum.reset_index(inplace=True)
weight_sum[["region", "nr_weight", "norm_weight", "norm_weight3"]]
```


```{python}
#| echo: true

norm_level = {"East": 10, "North": 20, "South": 30, "West": 50}

full_sample["norm_weight4"] = SampleWeight().normalize(
    samp_weight=full_sample["nr_weight"], 
    control=norm_level, 
    domain=full_sample["region"]
    )

weight_sum = full_sample.groupby(["region"]).sum()
weight_sum.reset_index(inplace=True)
weight_sum[["region", "nr_weight", "norm_weight", "norm_weight3", "norm_weight4",]]
```